[package]
name = "mp4"
version = "0.2.0"
edition = "2021"
authors = ["Luo <gnulinux@126.com>", "Even Solberg (even.solberg@gmail.com)"]

[lib]
name = "mp4"
path = "src/lib.rs"

[dependencies]
byteorder = "1.4.3"
